<template>
  <a-panel-section>
    <a-title
      :title="$t('company.management.order.salesTitle')"
      :subtitle="$t('company.management.order.salesDescription')"
      size="x-large"
    />
  </a-panel-section>
</template>
