module.exports = {
  source: ['packages/shared/design-system/src/sd-input.json'],
  fileHeader: {
    autoGeneratedFileHeader: () => {
      return [`Do not edit directly, this file was auto-generated`];
    },
  },
  platforms: {
    scss: {
      transformGroup: 'scss',
      buildPath: 'packages/shared/design-system/tokens/',
      prefix: 'figma',
      files: [
        {
          destination: 'variables.scss',
          format: 'scss/variables',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
  },
};